# -*- coding: utf-8 -*-
"""Visualizing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NZ6V5T-ZvdEvsdsKespsKh9ElwID0feC
"""

!pip install pandas matplotlib

import pandas as pd
import matplotlib.pyplot as plt

data_biden = {
    "Polarity": [
        0.0, 0.0, -0.25, -0.2, -0.3, 0.2619, 0.0, -0.1, 0.0417, 0.275, 0.0, 0.05, -0.0925,
        0.0167, -0.05, -0.1, 0.225, 0.05, 0.0, -0.1, 0.0, -0.125, 0.05, 0.0, -0.1, 0.0,
        0.1661, 0.125, 0.0, 0.1375, 0.1042, 0.0, 0.0
    ],
    "Subjectivity": [
        0.0, 0.0, 0.5, 0.2533, 0.4333, 0.3452, 0.0, 0.55, 0.495, 0.3292, 0.0, 0.4625, 0.4375,
        0.2333, 0.05, 0.1, 0.45, 0.15, 0.0, 0.1, 0.0, 0.375, 0.2, 0.0, 0.1, 0.0,
        0.5563, 0.625, 0.0, 0.6875, 0.7, 0.0, 0.0
    ]
}

df_biden = pd.DataFrame(data_biden)

# Plotting sentiment polarity and subjectivity
plt.figure(figsize=(14, 7))

plt.subplot(1, 2, 1)
plt.plot(df_biden['Polarity'], marker='o', linestyle='-')
plt.title('Joe Biden Speech Polarity')
plt.xlabel('Speeches')
plt.ylabel('Polarity')
plt.axhline(0, color='red', linewidth=0.5, linestyle='--')
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(df_biden['Subjectivity'], marker='o', color='green', linestyle='-')
plt.title('Joe Biden Speech Subjectivity')
plt.xlabel('Speeches')
plt.ylabel('Subjectivity')
plt.axhline(0.5, color='red', linewidth=0.5, linestyle='--')
plt.grid(True)

plt.tight_layout()
plt.show()

import pandas as pd


polarity = [
    0.0, -0.2, 0.0, 0.15, 0.3, -0.1333, 0.3222, -0.1, 0.225, 0.5, -0.08125, 0.5, -0.45, -0.328125, -0.125,
    # Diğer polarity değerleri...
]
subjectivity = [
    0.0, 0.3, 0.0, 0.25, 0.3556, 0.2167, 0.5333, 0.1, 0.45, 0.5, 0.69375, 0.5, 0.5, 0.454375, 0.19,

]

len_polarity = len(polarity)
len_subjectivity = len(subjectivity)


if len_polarity > len_subjectivity:
    subjectivity.extend([0.0] * (len_polarity - len_subjectivity))
elif len_subjectivity > len_polarity:
    polarity.extend([0.0] * (len_subjectivity - len_polarity))


data_trump = {
    "Polarity": polarity,
    "Subjectivity": subjectivity
}
df_trump = pd.DataFrame(data_trump)

print(df_trump.head())  # İlk beş veriyi kontrol et

import matplotlib.pyplot as plt

plt.figure(figsize=(14, 7))

plt.subplot(1, 2, 1)
plt.plot(df_trump['Polarity'], marker='o', linestyle='-', color='red')
plt.title('Donald Trump Speech Polarity')
plt.xlabel('Speech Index')
plt.ylabel('Polarity')
plt.axhline(0, color='blue', linewidth=0.5, linestyle='--')
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(df_trump['Subjectivity'], marker='o', color='green', linestyle='-')
plt.title('Donald Trump Speech Subjectivity')
plt.xlabel('Speech Index')
plt.ylabel('Subjectivity')
plt.axhline(0.5, color='blue', linewidth=0.5, linestyle='--')
plt.grid(True)

plt.tight_layout()
plt.show()